#!/bin/bash
# #SBATCH --qos=high
#SBATCH --job-name=bio-airlift
#SBATCH --partition=standard
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=36
#SBATCH --time=48:00:00
#SBATCH --account=bpms
#SBATCH --output=log.out

module purge
ml PrgEnv-cray
source /projects/gas2fuels/ofoam_cray_mpich/OpenFOAM-dev/etc/bashrc

module purge
module load openmpi/1.10.7/gcc-7.3.0
module load gcc
source /projects/bpms/openfoam/OpenFOAM-dev/etc/bashrc
. ./presteps.sh
srun -n 144 birdmultiphaseEulerFoam -parallel
