#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake -j 20 $targetType phaseSystem
wmake -j 20 $targetType populationBalance
wmake -j 20 $targetType thermophysicalTransportModels
wmake -j 20 $targetType reactions
wmake -j 20 $targetType momentumTransportModels
wmake $targetType

wmake -j 20 $targetType fvModels
wmake -j 20 $targetType functionObjects

#------------------------------------------------------------------------------
