#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mv constant/NofvModels constant/fvModels 

echo -e " - Manipulate default specie"
sed 's|^defaultSpecie.*|defaultSpecie air;|' -i constant/thermophysicalProperties.gas

echo -e " - Manipulate controlDict"
sed 's|^endTime.*|endTime   160;|' -i system/controlDict
sed 's|^deltaT.*|deltaT          0.0001;|' -i system/controlDict
sed 's|^adjustTimeStep.*|adjustTimeStep  no;//yes;//|' -i system/controlDict

## runApplication $(getApplication)
#------------------------------------------------------------------------------
