#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

if [ -n "$WM_PROJECT_DIR" ]; then
    . $WM_PROJECT_DIR/bin/tools/CleanFunctions
    cleanCase
else
    echo "WARNING: could not run cleanCase, OpenFOAM env not found"
fi

# Remove 0
[ -d "0" ] && rm -rf 0

# rm -f constant/triSurface/*.eMesh
# [ -d "constant/extendedFeatureEdgeMesh" ] && rm -rf "constant/extendedFeatureEdgeMesh"
[ -d "constant/polyMesh" ] && rm -rf "constant/polyMesh"
[ -d "dynamicCode" ] && rm -rf "dynamicCode"
[ -d "processor*" ] && rm -rf "processor*"
# rm -f constant/fvModels
rm -f *.obj
rm -f *.stl
rm -f *.txt

#------------------------------------------------------------------------------
