#!/bin/bash
#SBATCH --job-name=utube_gmsh_test
#SBATCH --partition=short
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --time=04:00:00
#SBATCH --account=gas2fuels
#SBATCH --output=out.log
#SBATCH --error=error.log
module purge
module load openfoam/9-craympich
source ~/.bashrc
srun -n 16 biomultiphaseEulerFoam -parallel
