#!/bin/bash
#SBATCH --qos=high
#SBATCH --job-name=val2
#SBATCH --partition=debug
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --time=00:59:00
#SBATCH --account=gas2fuels

bash presteps.sh
#source /projects/gas2fuels/ofoam_cray_mpich/OpenFOAM-dev/etc/bashrc
module load openfoam/9-craympich
decomposePar -fileHandler collated
srun -n 16 birdmultiphaseEulerFoam -parallel -fileHandler collated
reconstructPar -newTimes
