#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake -j 4 $targetType phaseSystems
wmake -j 4 $targetType interfacialModels
wmake -j 4 $targetType interfacialCompositionModels
wmake -j 4 $targetType multiphaseCompressibleMomentumTransportModels
wmake -j 4 $targetType multiphaseReactions
multiphaseEulerFoam/Allwmake $targetType $*
wmake -j 4 $targetType functionObjects

#------------------------------------------------------------------------------
