#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.orig 0
m4 ./system/panel.m4 > ./system/blockMeshDict
runApplication blockMesh
runApplication setFields
runApplication decomposePar -fileHandler collated -latestTime
## runApplication $(getApplication)

#------------------------------------------------------------------------------
