#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove surface, features and solution
#rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
#rm -f constant/triSurface/*.eMesh > /dev/null 2>&1
#rm -rf constant/polyMesh > /dev/null 2>&1
#rm -rf processor* > /dev/null 2>&1
rm -rf 0
cleanCase
rm *.obj
rm *.stl

#------------------------------------------------------------------------------
