#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

numcores=4
wmake -j $numcores $targetType functionObjects
wmake -j $numcores $targetType interfacialCompositionModels
wmake -j $numcores $targetType interfacialModels
wmake -j $numcores $targetType phaseSystems


wmake -j $numcores $targetType multiphaseCompressibleMomentumTransportModels
wmake -j $numcores $targetType multiphaseReactions

multiphaseEulerFoam/Allwmake $targetType $*


#------------------------------------------------------------------------------
